### ISSUE TITLE
my computed tvec are totally wrong. 

### ISSUE THREAD

**Issue by chaowu2009** [meyiao/SimpleStereoVO#1]
The scale is totally wrong. Would you mind sharing your contact such that I can show my result?

Thanks.

**Comment by meyiao** [comment]
Hi, 
I'm glad that you are interested in this project. You can contact me through the Email : 215442894@qq.com
As mentioned in the introduction, I have tested my code on the KITTI dataset and the results were quite good. This dataset is very easy to handle, since the car's rotation rate is always small, so does the nonlinear effect !  If you use a dataset which is more challenging, the results could be very bad! 
You may send me your dataset, so we can check which part goes wrong!
